### ISSUE TITLE
small annoying typographic suggestion: a curly quote in the homepage headline

### ISSUE THREAD

**Issue by arrowtype** [alienlebarge/alienlebargech-v3#57]
Okay, first of all, I really love the design and content of the website! It seriously looks awesome, and there’s lots of great stuff to read, and I also like the choice of the sans-serif font. ;)

This is a small typographic thing that I feel slightly like a jerk for mentioning, but on the homepage, the headline uses a straight quote where I would technically expect a curly quote.

So, specifically, I think you could use option+shift+] to type an apostrophe in the [homepage.md](https://github.com/alienlebarge/alienlebargech-v3/blob/81a13b61a57929bfe235158fffc435df6693ff8b/src/_content/pages/homepage.md
):

```diff
- Hi, I'm Cédric
+ Hi, I’m Cédric
```

It’s possible that this might be tricky – e.g. the build might instead require an HTML entity (`&rdquo;`), or you might need a markdown plugin like smartypants (but there are also reasons to avoid an automated approach like that). Or, it’s also possible that you just prefer the straight quote, which is cool, too. I just wanted to point it out in case it’s a helpful little improvement, but it’s totally chill whether you decide to change it or not.

**Comment by alienlebarge** [comment]
Thanks for the feedback.

You are right. I don't know why it hasn't been fix sooner. This is the kind of thing I care about.

**Comment by arrowtype** [comment]
Nice, way to get in the quick fix! To be fair, straight quotes also look pretty nice on their own way, and in most cases (especially for a sans-serif font), it doesn't really matter that much. Still, I think the proper quote looks nice here!
